src/lib.rs
src/nullable_format.rs

When we merged the Nullable support to master, it turned out there were a few warnings.
This pull request resolves both of those.

Resolve Warnings from compiler and clippy.

---

Cargo.toml
src/lib.rs

In order to add xml support to swagger codegen, we need to add support for the error types used by serde-xml-rs during serialization and deserialization. 
This PR adds a conversion trait to generate ApiErrors from serde-xml-rs::Error.
The build currently pulls from a fork of serde-xml-rs, I will re-direct it to point at the official crate once the corresponding pull request to serde-xml-rs is accepted.

Add conversion of serde-xml-rs errors for xml support

---

src/auth.rs
src/base64_format.rs
src/lib.rs
src/nullable_format.rs

Enable `missing_docs` (warning), `missing_debug_implementations` (warning) and `unused_extern_crates` (error). Enforcing this now will make for nicer code in the future.
No need for a version bump, no actual code has changed

Enable useful warnings

---

.travis.yml

At https://travis-ci.org/Metaswitch/swagger-rs/jobs/318855166, the build was failing with
```
1.38s$ cargo install rustfmt --vers 0.9.0
Updating registry `https://github.com/rust-lang/crates.io-index`
Downloading rustfmt v0.9.0
Installing rustfmt v0.9.0
error: binary `cargo-fmt` already exists in destination
binary `rustfmt` already exists in destination
Add --force to overwrite
The command "cargo install rustfmt --vers 0.9.0" failed and exited with 101 during .
Your build has been stopped.
```
The only change since the previous version (which got past this point) seems to be the move from rustup 1.17.0 to rustup 1.18.0.
I'm not sure if this is the right fix, but it solves the problem (https://travis-ci.org/Metaswitch/swagger-rs/jobs/319001631).
@kw217, please can you review?

Force rustfmt install

---

.travis.yml

~~(This PR includes commits that are part of #24 - please don't review those here, and don't merge this until that is merged.)~~ Now rebased.
Add some checks that CHANGELOG has lines matching the current package version from Cargo.toml.

Check changelog up to date

---

src/composites.rs
src/drop_context.rs
src/lib.rs

This change adds a partial inverse of AddContext that wraps a Service that expects a hyper::Request, and takes a (hyper::Request, context) pair instead.  This allows services that just request a hyper::Request to be used in a CompositeService alongside swagger generated services.

Add DropContext as inverse of AddContext

---

CHANGELOG.md
src/drop_context.rs

DropContext isn't very usable because real-world Context-using Services won't match the trait bounds on C (`AddContext` isn't the only thing modifying context types).  However, the whole point is to ignore whatever the second component of the `Request` is, so `DropContext` should just be implemented over a wide-open `C`

Remove unnecessary type bounds from DropContext

---

CHANGELOG.md
src/context.rs

This change adds the SwaggerService trait to swagger-rs, this trait is used by swagger middlewares.

Add SwaggerContext trait used by swagger-codegen middleware

---

src/context.rs

This fixes:
```
Checking swagger v2.0.2 (/home/travis/build/Metaswitch/swagger-rs)
error: unused doc comment
--> src/context.rs:384:1
|
384 |   /// Create a default context type to export.
|   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
385 | / new_context_type!(
386 | |     ContextBuilder,
387 | |     EmptyContext,
388 | |     XSpanIdString,
389 | |     Option<AuthData>,
390 | |     Option<Authorization>
391 | | );
| |__- rustdoc does not generate documentation for macro expansions
|
= note: `-D unused-doc-comments` implied by `-D warnings`
= help: to document an item produced by a macro, the macro must produce the documentation as part of its expansion
```
seen in both master, and v2.

Fix clippy unused doc comment lint

---

CHANGELOG.md
src/base64_format.rs
src/composites.rs
src/connector.rs
src/context.rs
src/headers.rs
src/lib.rs

In Hyper 0.11, the following code will panic:
use hyper::header::{Authorization, Basic, Bearer, Headers};
fn main() {
let mut headers = Headers::default();
let basic = Basic { username: "richard".to_string(), password: None };
headers.set::<Authorization<Basic>>(Authorization(basic));
println!("Auth: {:?}", headers.get::<Authorization<Bearer>>());
}
This is because `std::any::TypeId::of<Authorization<Basic>>` and
`std::any::TypeId::of<Authorization<Bearer>>` don't match, but the header
name, `Authorization` does.
We provide a `.safe_get::<Authorization<Bearer>>` to workaround this issue.

Handle Hyper 0.11's Headers implementation

---

Cargo.toml
src/add_context.rs
src/base64_format.rs
src/composites.rs
src/connector.rs
src/context.rs
src/drop_context.rs
src/header.rs
src/lib.rs
src/nullable_format.rs

This updates swagger-rs to Rust 2018 edition.
This means we need Rust 1.31 to build - but given we don't have a policy other than "Builds on stable Rust", I don't think this constitutes an API break.

Update swagger-rs to Rust 2018 Edition

---

src/context.rs

With this, the various `make_context_X` macros never reference names from the local crate without fully qualifying them.  Without this, users of the macros would have to `use` various swagger traits/macros (or `#[macro_use]` the crate).

Make context macros self-contained

---

src/drop_context.rs

Since client middle-ware might need contexts too, this simply add a symmetric implementation of `swagger::client::Service` to the `DropContextService` middle-ware.

Make DropContextService a client middleware too

---

Cargo.toml

hyper-tls 0.4 is compatible with Hyper 0.13, not Hyper 0.12

Use hyper-tls 0.3 instead

---

CHANGELOG.md
src/header.rs

Currently services using the `AddContextService` will panic in a request is made with an X-Span-ID header with non-ASCII characters due to an `unwrap`. This change will instead create a new span ID in this scenario.

Don't panic in X-Span-ID handling of non-ASCII characters

---

src/add_context.rs
src/auth.rs
src/body.rs
src/composites.rs
src/context.rs
src/drop_context.rs

This is needed implicitly all over the place in hyper-land (and really in any async land where a future might not be pinned to a thread).
Also, takes advantage of `futures::future::BoxFuture` which is pretty much exactly what you had before only it's `+ Send` and has a space to write that it's `'static` explictly.

Ensure futures are Send and 'static

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/add_context.rs
src/auth.rs
src/connector.rs
src/context.rs
src/multipart.rs
src/nullable_format.rs

Currently if a OpenAPI model includes a nullable field, we can't use frunk to transmogrify it into a identical structure using `swagger::Nullable`

Add frunk support for swagger::Nullable

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/add_context.rs
src/auth.rs
src/connector.rs
src/context.rs
src/multipart.rs
src/nullable_format.rs

Forward merge of 114: Add frunk support for swagger::Nullable r=richardwhiuk a=richardwhiuk
Currently if a OpenAPI model includes a nullable field, we can't use frunk to transmogrify it into a identical structure using `swagger::Nullable`
Co-authored-by: Richard Whitehouse <richard.whitehouse@metaswitch.com>
Cherry-picked from 36f5300d9b9216946a58cf5b01730f18bc151f2e.

Merge #114 to master

---

Cargo.toml
src/nullable_format.rs

This reverts commit 92f6f85ff13c1b10b4621c2d6a6fcdfd6d98cfef.
This reverts https://github.com/Metaswitch/swagger-rs/pull/114 which caused problems due to https://github.com/lloydmeta/frunk/issues/143

Revert "Add frunk support for swagger::Nullable"

---

src/auth.rs

Required because the Api is required to be clone-able - https://github.com/OpenAPITools/openapi-generator/blob/master/modules/openapi-generator/src/main/resources/rust-server/server-make-service.mustache#L22

impl Clone for AllowAllAuthenticator

---

CHANGELOG.md
src/composites.rs

This fixes Composite Service support.
There's roughly two parts here:
- Re-introducing the equivalents of BoxedService and BoxedMakeService to avoid the inner code having to deal with boxing it's services, which makes the calling code elegant.
- Implementing Service twice for CompositeMakeService, for the specific Target types.
This is disappointing, but I believe unavoidable. The alternative workaround (adding a `Target: Clone` bound) doesn't work, as it causes the Rust compiler to mark Target as early bound as opposed to late bound, (see https://github.com/rust-lang/rfcs/blob/master/text/0387-higher-ranked-trait-bounds.md#distinguishing-early-vs-late-bound-lifetimes-in-impls ).
This means that the type no longer matches the requirement on MakeServiceRef - see …

Fix Composite service support in Hyper 0.13

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/one_any_of.rs
src/request_parser.rs

We are using a private API in serde, and they've changed the API in a patch release to remind us this is wrong:
https://github.com/serde-rs/serde/commit/dd1f4b483ee204d58465064f6e5bf5a457543b54
That's annoying, but there's no easy viable alternative. This API is used by serde_derive on an untagged enum ( see https://github.com/serde-rs/serde/blob/b0c99ed761d638f2ca2f0437522e6c35ad254d93/serde_derive/src/de.rs#L1627-L1645 ), which is basically what we have.
We can't use serde_derive, because we want specific semantics. The only alternative is re-implementing the `ContentRefDeserializer` and `Content` objects, which is clearly worse than depending on this private API.
I've asked in Discord and raised https://github.com/serde-rs/serde/issues/1947 to query the serde devs.
Signed-off-by: …

Workaround API break on private API in Serde 1.0.119

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/base64_format.rs
src/connector.rs
src/lib.rs

- Support Hyper 0.14 and match features
- Add new feature `tcp` to signal HTTP support
- Add new feature `tls` to signal HTTP(S) support
- Add new feature `client` to signal Client support
- Add new feature `server` to signal Server support
- Upgrade base64 to 0.13
- Upgrade tokio to 1.0

Upgrade to Hyper 0.14

---

CHANGELOG.md
src/lib.rs

While well intentioned, these make it too easy for server side business logic
to return ApiErrors without due care and attention.
As such, it's better for the calling code to explicitly provide the conversion
in cases where it's sensible.
Signed-off-by: Richard Whitehouse <richard.whitehouse@metaswitch.com>

Remove implicit conversions for ApiError

---

.travis.yml
CHANGELOG.md
Cargo.toml
src/composites.rs
src/lib.rs
src/one_any_of.rs
src/request_parser.rs

This merges forward a couple of features merged into v5 - primarily
- https://github.com/Metaswitch/swagger-rs/pull/139 - Support conversion for AnyOf and OneOf
- https://github.com/Metaswitch/swagger-rs/pull/140 - Expose CompositeMakeServiceEntry
It also fixes a clippy lint we were living with in v5.

Forward merge v5 fixes

---

Cargo.toml
src/composites.rs

Andy,
This adds support to CompositeMakeService to support Unix domain sockets.
Tested against a microservice internally.
Signed-off-by: Richard Whitehouse <richard.whitehouse@metaswitch.com>

Support Unix Domain Sockets

---

CHANGELOG.md
Cargo.toml
release-changelog.sh

Remove Chrono, as it's not used, and it's vulnerable to security vulnerabilities - particularly RUSTSEC-2020-0159 and RUSTSEC-2020-0071

Remove Chrono

---

src/one_any_of.rs

Previously, the docs had literally $t and $i symbols - this fixes
them to have the actual text.
This resolves #152.
Signed-off-by: Richard Whitehouse <richard.whitehouse@metaswitch.com>

Improve docs for oneOf/anyOf types

---

src/base64_format.rs
src/header.rs
src/multipart/form.rs

This fixes all clippy warnings in Rust 1.70

Fix clippy warnings in Rust 1.70

---

CHANGELOG.md
Cargo.toml

This applies https://github.com/Metaswitch/swagger-rs/pull/170 without taking a breaking change.
We are vulnerable to the concerns discussed in https://github.com/rust-lang/cargo/issues/10599 - but on balance, this is a better trade-off, and downstream users can force the "right" resolution.

Support serde_valid 0.16

---

Cargo.toml
src/lib.rs

Fix:
```
Documenting swagger v6.4.0
error[E0554]: `#![feature]` may not be used on the stable release channel
--> swagger-6.4.0/src/lib.rs:40:18
|
40 | #![cfg_attr(doc, feature(doc_auto_cfg))]
|                  ^^^^^^^^^^^^^^^^^^^^^
For more information about this error, try `rustc --explain E0554`.
error: could not document `swagger`
```
We match the fix done in tower:
- src/lib.rs - https://github.com/tower-rs/tower/blob/bf4ea948346c59a5be03563425a7d9f04aadedf2/tower/src/lib.rs#L10C1-L10C53
- Cargo.toml - https://github.com/tower-rs/tower/blob/bf4ea948346c59a5be03563425a7d9f04aadedf2/tower/Cargo.toml#L98-L100

Fix doc build breakage on stable
